### ISSUE TITLE
[Conversion] Fate Condensed

### ISSUE THREAD

**Issue by Rarstyak** [Obsidian-TTRPG-Community/TTRPG-Community-Admin#15]
# Info

**Conversion Project:** Fate Condensed

**Repo Link:** [https://github.com/Rarstyak/Fate-Condensed-SRD](https://github.com/Rarstyak/Fate-Condensed-SRD)

**Assistance** I am (**not looking**) for assistance.

**Comment by sigrunixia** [comment]
I have moved this to the Admin Repo as this will be the new home of the "Conversion" projects going forward. :)

**Comment by sigrunixia** [comment]
Also, I looked at the repo and it looks rather complete (But I haven't played with Fate yet). What would you say the status is on it now?

**Comment by Rarstyak** [comment]
I think I completed it in February as far as the content goes. I wanted to lint it as well, but the community was still discussing which rules to use at the time, and I'd forgotten to follow up.

**Comment by sigrunixia** [comment]
Oh, that was more for stuff within the repo! As yours is in separate, you are exempt. :)

**Comment by sigrunixia** [comment]
Marking this as completed. Also, I added this repo to the Obsidian Hub update I sent in for a PR. :)
